#!/usr/bin/env python3
"""
Nightwatch Self-Healing — fix tracked failures via Claude Code in worktrees.

Runs nightly at 3 AM. Queries CRM for failure tasks tagged nightwatch+self-improve,
invokes Claude Code in isolated git worktrees to fix each one, and creates draft PRs.

Usage:
    python brain/scripts/nightwatch-heal.py           # Normal run
    python brain/scripts/nightwatch-heal.py --dry-run  # Query tasks only, skip Claude Code
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from brain.scripts.nightwatch_lib import (
    check_pause_condition,
    cleanup_worktree,
    create_nightwatch_task,
    create_worktree,
    determine_scope,
    extract_pr_url,
    get_merge_rate,
    get_tasks,
    invoke_claude_code,
    read_memory_block,
    resolve_nightwatch_task,
    setup_logging,
    today_str,
    write_memory_block,
    write_status_file,
)

log = setup_logging("nightwatch-heal")

MAX_PRS = 3

HEAL_SYSTEM_PROMPT = """\
You are fixing a bug in the Robothor project. You are in an isolated git worktree.

Rules:
1. Make ONLY the changes described. Do not refactor unrelated code.
2. Run relevant tests: /home/philip/robothor/venv/bin/python -m pytest <test_file> -v
3. For manifest changes: /home/philip/robothor/venv/bin/python scripts/validate_agents.py
4. Commit with conventional messages (fix:/chore:) with [nightwatch] suffix.
5. Push: git push -u origin <branch>
6. Create draft PR: gh pr create --draft --label nightwatch --title "<title>" --body "<body>"
7. If tests fail, do NOT create a PR. Stop and explain why.
8. NEVER modify: runner.py, daemon.py, scheduler.py, conftest.py, run_tests.sh
9. The PR body must include: Summary, Risk Assessment (LOW/MEDIUM/HIGH), Validation checklist, and "Generated by Nightwatch Self-Healing".
"""

HEAL_TOOLS = "Read,Edit,Write,Glob,Grep,Bash(git:*,pytest:*,python:*,gh:*)"
HEAL_BUDGET = 0.75


def build_heal_prompt(task: dict, scope: str) -> str:
    """Build the prompt for a heal task."""
    scope_rules = {
        "config": "You may ONLY modify YAML manifests in docs/agents/ and brain/memory/ status files.",
        "config+instructions": "You may modify YAML manifests in docs/agents/ and instruction files in brain/agents/.",
        "config+instructions+code": "You may modify manifests, instructions, and Python code in robothor/.",
    }

    return f"""\
Fix the following bug/failure in the Robothor project.

## Task
Title: {task.get('title', 'Unknown')}
ID: {task.get('id', 'Unknown')}
Priority: {task.get('priority', 'normal')}

## Description
{task.get('body', 'No description provided.')}

## Scope Rules
{scope_rules.get(scope, scope_rules['config'])}

## Branch
You are on branch: {task.get('_branch', 'nightwatch/fix')}
The repo root is the current working directory.

## Steps
1. Read and understand the files mentioned in the description.
2. Make the minimal fix.
3. Run tests to verify.
4. Commit, push, and create a draft PR.
5. Output the PR URL in your final response.
"""


def slugify(title: str) -> str:
    """Convert a task title to a branch-safe slug."""
    slug = title.lower()
    slug = "".join(c if c.isalnum() or c == "-" else "-" for c in slug)
    slug = "-".join(part for part in slug.split("-") if part)
    return slug[:50]


def main(dry_run: bool = False) -> None:
    log.info("Nightwatch heal starting (dry_run=%s)", dry_run)

    # Step 1: Check pause condition
    nightwatch_log = read_memory_block("nightwatch_log")
    if check_pause_condition(nightwatch_log):
        log.warning("Nightwatch is PAUSED due to consecutive rejections")
        write_status_file("brain/memory/overnight-pr-status.md", (
            f"# Overnight PR Status\n\n"
            f"Last run: {datetime.now().isoformat()}\n"
            f"Status: PAUSED — 3 consecutive PR rejections\n"
        ))
        return

    # Step 2: Check merge rate and determine scope
    merge_rate = get_merge_rate(nightwatch_log)
    scope = determine_scope(merge_rate)
    log.info("Merge rate: %.0f%%, scope: %s", merge_rate * 100, scope)

    # Step 3: Get tasks
    tasks = get_tasks(tags=["nightwatch", "self-improve"], status="TODO", limit=MAX_PRS)
    if not tasks:
        log.info("No tasks to process")
        write_status_file("brain/memory/overnight-pr-status.md", (
            f"# Overnight PR Status\n\n"
            f"Last run: {datetime.now().isoformat()}\n"
            f"PRs created: 0\n"
            f"Tasks available: 0\n"
        ))
        return

    log.info("Found %d tasks to process", len(tasks))

    if dry_run:
        for t in tasks:
            log.info("  [DRY RUN] Task: %s (priority=%s)", t.get("title"), t.get("priority"))
        return

    # Step 4: Process each task
    date = today_str()
    prs_created = []
    tasks_skipped = []

    for task in tasks[:MAX_PRS]:
        task_id = task.get("id", "unknown")
        title = task.get("title", "untitled")
        slug = slugify(title)
        branch = f"nightwatch/{date}/{slug}"
        task["_branch"] = branch

        log.info("Processing task: %s (%s)", title, task_id)

        worktree_path = None
        try:
            # Create worktree
            worktree_path = create_worktree(branch)

            # Invoke Claude Code
            prompt = build_heal_prompt(task, scope)
            result = invoke_claude_code(
                cwd=worktree_path,
                prompt=prompt,
                system_prompt=HEAL_SYSTEM_PROMPT,
                allowed_tools=HEAL_TOOLS,
                budget=HEAL_BUDGET,
                timeout=600,
            )

            # Check for PR URL
            pr_url = extract_pr_url(result)
            if pr_url:
                log.info("PR created: %s", pr_url)
                prs_created.append({"task_id": task_id, "title": title, "pr_url": pr_url})
                resolve_nightwatch_task(task_id, f"Draft PR created: {pr_url}")
            else:
                error = result.get("error", "No PR created — likely test failure")
                log.warning("No PR for task %s: %s", task_id, error)
                tasks_skipped.append({"task_id": task_id, "title": title, "reason": error})

        except Exception as e:
            log.error("Error processing task %s: %s", task_id, e)
            tasks_skipped.append({"task_id": task_id, "title": title, "reason": str(e)})

        finally:
            if worktree_path:
                cleanup_worktree(worktree_path)

    # Step 5: Write results
    now = datetime.now().isoformat()

    # Update nightwatch_log memory block
    log_entry = f"[{date}] heal: PRs created: {len(prs_created)}, skipped: {len(tasks_skipped)}"
    if prs_created:
        log_entry += "\n" + "\n".join(
            f"  PR: {pr['pr_url']} ({pr['title']})" for pr in prs_created
        )
    updated_log = nightwatch_log.rstrip() + "\n" + log_entry + "\n"
    # Trim to keep last 50 entries
    lines = updated_log.strip().split("\n")
    if len(lines) > 100:
        lines = lines[-100:]
    write_memory_block("nightwatch_log", "\n".join(lines))

    # Write status file
    pr_list = "\n".join(
        f"- [{pr['title']}]({pr['pr_url']})" for pr in prs_created
    ) or "None"
    skipped_list = "\n".join(
        f"- {s['title']}: {s['reason'][:80]}" for s in tasks_skipped
    ) or "None"

    write_status_file("brain/memory/overnight-pr-status.md", (
        f"# Overnight PR Status\n\n"
        f"Last run: {now}\n"
        f"Mode: heal\n"
        f"Scope: {scope} (merge rate: {merge_rate:.0%})\n"
        f"PRs created: {len(prs_created)}\n"
        f"Tasks skipped: {len(tasks_skipped)}\n\n"
        f"## PRs Created\n{pr_list}\n\n"
        f"## Skipped\n{skipped_list}\n"
    ))

    # Step 6: Create review task if PRs were created
    if prs_created:
        pr_summary = "\n".join(
            f"- {pr['title']}: {pr['pr_url']}" for pr in prs_created
        )
        create_nightwatch_task(
            title=f"Review Nightwatch Heal PRs — {date}",
            body=(
                f"{len(prs_created)} draft PR(s) awaiting review:\n\n"
                f"{pr_summary}\n\n"
                f"Scope: {scope}\n"
                f"Generated by Nightwatch Self-Healing"
            ),
            tags=["nightwatch", "review-needed", "needs-philip"],
            priority="high",
            assigned_to="main",
        )

    log.info(
        "Nightwatch heal complete: %d PRs created, %d skipped",
        len(prs_created), len(tasks_skipped),
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Nightwatch Self-Healing")
    parser.add_argument("--dry-run", action="store_true", help="Query tasks only, skip Claude Code")
    args = parser.parse_args()
    main(dry_run=args.dry_run)
