#!/usr/bin/env python3
"""
Consolidated Nightwatch — single nightly autonomous improvement agent.

Replaces: nightwatch-heal.py, nightwatch-build.py, nightwatch-research.py

Runs once per night, produces max 1 draft PR using Opus 4.6 via Claude Code CLI.
Finds work from: backlog file > fleet failures > self-identified improvements.

Usage:
    python brain/scripts/nightwatch.py                # Normal run
    python brain/scripts/nightwatch.py --dry-run      # Select work only, skip execution
    python brain/scripts/nightwatch.py --backlog-only  # Only consider backlog items
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from brain.scripts.nightwatch_lib import (
    REPO_ROOT,
    check_off_backlog_item,
    check_pause_condition,
    cleanup_worktree,
    create_nightwatch_task,
    create_worktree,
    extract_pr_url,
    find_self_improvements,
    invoke_claude_code,
    parse_backlog,
    read_memory_block,
    resolve_nightwatch_task,
    setup_logging,
    slugify,
    today_str,
    write_memory_block,
    write_status_file,
)

log = setup_logging("nightwatch")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

MODEL = "claude-opus-4-6"
BUDGET = 3.00  # USD per run
TIMEOUT = 900  # 15 minutes
ALLOWED_TOOLS = "Read,Edit,Write,Glob,Grep,Bash(git:*,pytest:*,python:*,gh:*,find:*)"

BACKLOG_PATH = REPO_ROOT / "brain" / "nightwatch-backlog.md"
STATUS_PATH = "brain/memory/overnight-pr-status.md"

SYSTEM_PROMPT = """\
You are Nightwatch, an autonomous code improvement agent for the Robothor project.
You run once per night in an isolated git worktree. Your goal is to make one
high-quality, focused improvement and create a draft PR for Philip to review.

## Rules
1. Make ONLY the changes described in your task. Do not refactor unrelated code.
2. Run relevant tests: /home/philip/robothor/venv/bin/python -m pytest <test_file> -v
3. For manifest changes: /home/philip/robothor/venv/bin/python scripts/validate_agents.py
4. Commit with conventional messages (fix:/feat:/chore:/test:/docs:) with [nightwatch] suffix.
5. Push: git push -u origin <branch>
6. Create draft PR: gh pr create --draft --label nightwatch --title "<title>" --body "<body>"
7. If tests fail and you cannot fix them, do NOT create a PR. Stop and explain why.
8. NEVER modify: runner.py, daemon.py, scheduler.py, conftest.py, run_tests.sh
9. NEVER push to main or master.
10. NEVER commit secrets, credentials, or .env files.
11. Keep the PR focused — one logical change per PR.

## PR Body Format
Include in the PR body:
- **Summary**: What changed and why (2-3 sentences)
- **Risk Assessment**: LOW / MEDIUM / HIGH with brief justification
- **Test Plan**: What tests you ran or added
- Footer: "Generated by Nightwatch"

## What You Can Do
- Fix bugs in Python code under robothor/ and brain/
- Improve test coverage for under-tested modules
- Clean up dead code, unused imports, stale config
- Fix agent manifests (docs/agents/*.yaml) and instructions (brain/agents/*.md)
- Implement small, well-scoped features
- Address TODO/FIXME markers

## What You Should Avoid
- Large refactors touching many files
- Changes to core infrastructure (runner, daemon, scheduler, test infrastructure)
- Adding new dependencies without clear justification
- Speculative features not in the task description
"""


# ---------------------------------------------------------------------------
# Work item
# ---------------------------------------------------------------------------

@dataclass
class WorkItem:
    source: str          # "backlog" | "fleet_failure" | "self_identified"
    title: str
    description: str
    priority: str        # "P1" | "P2" | "P3"
    category: str        # "bugfix" | "test" | "quality" | "feature" | "cleanup"
    backlog_line: int | None = None
    crm_task_id: str | None = None


# ---------------------------------------------------------------------------
# Phase 1: Work selection (no LLM, no worktree, $0 cost)
# ---------------------------------------------------------------------------

def select_from_backlog() -> WorkItem | None:
    """Pick the top unchecked backlog item."""
    items = parse_backlog(BACKLOG_PATH)
    if not items:
        return None

    top = items[0]
    text = top["text"]

    # Infer category from keywords
    category = "feature"
    lower = text.lower()
    if any(w in lower for w in ("test", "coverage", "pytest")):
        category = "test"
    elif any(w in lower for w in ("fix", "bug", "error", "crash")):
        category = "bugfix"
    elif any(w in lower for w in ("clean", "remove", "dead", "unused", "import")):
        category = "cleanup"
    elif any(w in lower for w in ("refactor", "quality", "todo", "fixme")):
        category = "quality"

    return WorkItem(
        source="backlog",
        title=text,
        description=text,
        priority=top["priority"],
        category=category,
        backlog_line=top["line_number"],
    )


def select_from_fleet_failures() -> WorkItem | None:
    """Pick the most impactful recent fleet failure."""
    try:
        from robothor.engine.analytics import get_failure_patterns, get_fleet_health
    except ImportError:
        log.warning("Could not import analytics module — skipping fleet analysis")
        return None

    try:
        result = get_failure_patterns(hours=24)
        # Result may be a dict with 'patterns' key or a list directly
        if isinstance(result, dict):
            patterns = result.get("patterns", [])
        else:
            patterns = result or []
        if not patterns:
            return None

        # Pick the pattern with the most failures
        top = max(patterns, key=lambda p: p.get("count", 0))
        count = top.get("count", 0)
        if count < 3:
            # Not worth a PR for fewer than 3 occurrences
            return None

        agent_id = top.get("agent_id", "unknown")
        error_type = top.get("error_type", "unknown")
        sample = top.get("sample_messages", [""])[0][:200] if top.get("sample_messages") else ""

        return WorkItem(
            source="fleet_failure",
            title=f"Fix {error_type} failures in {agent_id} agent",
            description=(
                f"The `{agent_id}` agent has had {count} `{error_type}` failures "
                f"in the last 24 hours.\n\n"
                f"Sample error:\n```\n{sample}\n```\n\n"
                f"Investigate the root cause in the agent's manifest "
                f"(`docs/agents/{agent_id}.yaml`), instruction file, and any "
                f"Python code it depends on. Fix the underlying issue."
            ),
            priority="P1" if count >= 5 else "P2",
            category="bugfix",
        )

    except Exception as e:
        log.warning("Fleet failure analysis failed: %s", e)
        return None


def select_self_improvement() -> WorkItem | None:
    """Pick the top self-identified improvement."""
    try:
        improvements = find_self_improvements(REPO_ROOT)
    except Exception as e:
        log.warning("Self-improvement scan failed: %s", e)
        return None

    if not improvements:
        return None

    top = improvements[0]
    return WorkItem(
        source="self_identified",
        title=top["title"],
        description=top["description"],
        priority=top.get("priority", "P3"),
        category=top.get("category", "quality"),
    )


def select_work(backlog_only: bool = False) -> WorkItem | None:
    """Select a single work item using priority cascade."""

    # 1. Backlog (always checked first)
    item = select_from_backlog()
    if item:
        log.info("Selected from backlog: %s", item.title)
        return item

    if backlog_only:
        log.info("Backlog-only mode, no backlog items found")
        return None

    # 2. Fleet failures
    item = select_from_fleet_failures()
    if item:
        log.info("Selected from fleet failures: %s", item.title)
        return item

    # 3. Self-identified improvements
    item = select_self_improvement()
    if item:
        log.info("Selected self-improvement: %s", item.title)
        return item

    log.info("No work found from any source")
    return None


# ---------------------------------------------------------------------------
# Phase 2: Execution (worktree + Claude Code)
# ---------------------------------------------------------------------------

def build_prompt(item: WorkItem, branch: str) -> str:
    """Build the task prompt for Claude Code."""
    return f"""\
You have one task tonight. Complete it thoroughly, then create a draft PR.

## Task
**{item.title}**
Category: {item.category}
Source: {item.source}

## Description
{item.description}

## Branch
You are on branch: {branch}
The repo root is the current working directory.

## Steps
1. Read and understand the relevant code. Use Glob and Grep to find related files.
2. Implement the change. Be surgical — change only what is needed.
3. If adding/fixing code, ensure test coverage exists. Add tests if missing.
4. Run tests: /home/philip/robothor/venv/bin/python -m pytest <relevant_test> -v
5. For agent manifest changes: /home/philip/robothor/venv/bin/python scripts/validate_agents.py
6. Commit with a conventional commit message and [nightwatch] suffix.
7. Push: git push -u origin {branch}
8. Create draft PR: gh pr create --draft --label nightwatch --title "<title>" --body "<body>"
9. Output the PR URL in your final response.

If tests fail and you cannot fix them, do NOT create a PR. Stop and explain what went wrong.
"""


def execute(item: WorkItem) -> tuple[str | None, str | None]:
    """Execute the work item in an isolated worktree.

    Returns (pr_url, error_message). One will be None.
    """
    date = today_str()
    slug = slugify(item.title)
    branch = f"nightwatch/{date}/{slug}"

    worktree_path = None
    try:
        worktree_path = create_worktree(branch)

        prompt = build_prompt(item, branch)
        result = invoke_claude_code(
            cwd=worktree_path,
            prompt=prompt,
            system_prompt=SYSTEM_PROMPT,
            allowed_tools=ALLOWED_TOOLS,
            budget=BUDGET,
            timeout=TIMEOUT,
            model=MODEL,
        )

        pr_url = extract_pr_url(result)
        if pr_url:
            log.info("PR created: %s", pr_url)
            return pr_url, None
        else:
            error = result.get("error", "No PR created — likely test failure or scope issue")
            log.warning("No PR created: %s", error)
            return None, error

    except Exception as e:
        log.error("Execution failed: %s", e)
        return None, str(e)

    finally:
        if worktree_path:
            cleanup_worktree(worktree_path)


# ---------------------------------------------------------------------------
# Phase 3: Tracking (update state)
# ---------------------------------------------------------------------------

def track_result(
    item: WorkItem,
    pr_url: str | None,
    error: str | None,
    nightwatch_log: str,
) -> None:
    """Update memory blocks, status files, backlog, and CRM tasks."""
    date = today_str()
    now = datetime.now().isoformat()

    # 1. Update nightwatch_log memory block
    if pr_url:
        log_entry = f"[{date}] {item.source}: \"{item.title}\" → {pr_url}"
    else:
        reason = (error or "unknown")[:100]
        log_entry = f"[{date}] {item.source}: \"{item.title}\" → FAILED: {reason}"

    updated_log = nightwatch_log.rstrip() + "\n" + log_entry + "\n"
    # Keep last 100 lines
    lines = updated_log.strip().split("\n")
    if len(lines) > 100:
        lines = lines[-100:]
    write_memory_block("nightwatch_log", "\n".join(lines))

    # 2. Write status file
    status = "PR created" if pr_url else f"Failed: {error}"
    write_status_file(STATUS_PATH, (
        f"# Overnight PR Status\n\n"
        f"Last run: {now}\n"
        f"Source: {item.source}\n"
        f"Task: {item.title}\n"
        f"Category: {item.category}\n"
        f"Status: {status}\n"
        f"Model: {MODEL}\n"
        + (f"PR: {pr_url}\n" if pr_url else "")
    ))

    # 3. Check off backlog item
    if item.backlog_line and pr_url:
        check_off_backlog_item(BACKLOG_PATH, item.backlog_line, pr_url)

    # 4. Resolve CRM task if applicable
    if item.crm_task_id and pr_url:
        resolve_nightwatch_task(item.crm_task_id, f"Draft PR created: {pr_url}")

    # 5. Create review task for Philip if PR was created
    if pr_url:
        create_nightwatch_task(
            title=f"Review Nightwatch PR — {date}",
            body=(
                f"Nightwatch created a draft PR:\n\n"
                f"- **Task**: {item.title}\n"
                f"- **Source**: {item.source}\n"
                f"- **Category**: {item.category}\n"
                f"- **PR**: {pr_url}\n\n"
                f"Generated by Nightwatch"
            ),
            tags=["nightwatch", "review-needed", "needs-philip"],
            priority="high",
            assigned_to="main",
        )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(dry_run: bool = False, backlog_only: bool = False) -> None:
    log.info("Nightwatch starting (dry_run=%s, backlog_only=%s)", dry_run, backlog_only)

    # Check pause condition
    nightwatch_log = read_memory_block("nightwatch_log")
    if check_pause_condition(nightwatch_log):
        log.warning("Nightwatch is PAUSED — 3 consecutive PR rejections")
        write_status_file(STATUS_PATH, (
            f"# Overnight PR Status\n\n"
            f"Last run: {datetime.now().isoformat()}\n"
            f"Status: PAUSED — 3 consecutive PR rejections\n"
        ))
        return

    # Phase 1: Select work
    item = select_work(backlog_only=backlog_only)
    if not item:
        log.info("No work found — system is healthy and backlog is empty")
        write_status_file(STATUS_PATH, (
            f"# Overnight PR Status\n\n"
            f"Last run: {datetime.now().isoformat()}\n"
            f"Status: No work found\n"
        ))
        return

    log.info(
        "Selected work: [%s] %s (source=%s, category=%s)",
        item.priority, item.title, item.source, item.category,
    )

    if dry_run:
        log.info("[DRY RUN] Would execute: %s", item.title)
        log.info("[DRY RUN] Description: %s", item.description[:200])
        return

    # Phase 2: Execute
    pr_url, error = execute(item)

    # Phase 3: Track results
    track_result(item, pr_url, error, nightwatch_log)

    if pr_url:
        log.info("Nightwatch complete — PR created: %s", pr_url)
    else:
        log.info("Nightwatch complete — no PR created: %s", error)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Consolidated Nightwatch Agent")
    parser.add_argument("--dry-run", action="store_true", help="Select work only, skip execution")
    parser.add_argument("--backlog-only", action="store_true", help="Only consider backlog items")
    args = parser.parse_args()
    main(dry_run=args.dry_run, backlog_only=args.backlog_only)
