#!/usr/bin/env python3
"""
DEPRECATED — replaced by brain/scripts/nightwatch.py (consolidated nightwatch agent).
This file is kept for git history. Use nightwatch.py instead.

---
Nightwatch Self-Improving — Phase B: Build.

Runs weekly (Monday 3 AM). Takes feature tasks from research phase,
invokes Claude Code in isolated git worktrees to implement each one,
and creates draft PRs.

Usage:
    python brain/scripts/nightwatch-build.py           # Normal run
    python brain/scripts/nightwatch-build.py --dry-run  # Query tasks only, skip Claude Code
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from brain.scripts.nightwatch_lib import (
    cleanup_worktree,
    create_nightwatch_task,
    create_worktree,
    extract_pr_url,
    get_tasks,
    invoke_claude_code,
    read_memory_block,
    resolve_nightwatch_task,
    setup_logging,
    today_str,
    write_memory_block,
    write_status_file,
)

log = setup_logging("nightwatch-build")

MAX_PRS = 2
BUILD_BUDGET = 1.50

BUILD_SYSTEM_PROMPT = """\
You are adding a new feature to the Robothor agent engine. You are in an isolated git worktree.

Rules:
1. Implement the feature described in the task. Follow existing code patterns.
2. Add tests for new functionality in the appropriate test file.
3. Run tests: /home/philip/robothor/venv/bin/python -m pytest robothor/engine/tests/ -v -x
4. For manifest changes: /home/philip/robothor/venv/bin/python scripts/validate_agents.py
5. Commit with conventional messages (feat:) with [nightwatch] suffix.
6. Push: git push -u origin <branch>
7. Create draft PR: gh pr create --draft --label nightwatch --label feature --title "<title>" --body "<body>"
8. If tests fail, fix them. If you can't fix them, stop and explain why.
9. NEVER modify test infrastructure (conftest.py, run_tests.sh).
10. Keep the PR focused — one feature per PR.
11. The PR body must include: Summary, Test Plan, Risk Assessment, and "Generated by Nightwatch Self-Improving".
"""

BUILD_TOOLS = "Read,Edit,Write,Glob,Grep,Bash(git:*,pytest:*,python:*,gh:*)"


def build_feature_prompt(task: dict) -> str:
    """Build the prompt for a feature task."""
    return f"""\
Implement the following feature in the Robothor agent engine.

## Task
Title: {task.get('title', 'Unknown')}
ID: {task.get('id', 'Unknown')}
Priority: {task.get('priority', 'normal')}

## Description
{task.get('body', 'No description provided.')}

## Branch
You are on branch: {task.get('_branch', 'feature/build')}
The repo root is the current working directory.

## Steps
1. Read the existing code to understand patterns and conventions.
2. Implement the feature with minimal, focused changes.
3. Add tests covering the new functionality.
4. Run the test suite to verify nothing breaks.
5. Commit, push, and create a draft PR.
6. Output the PR URL in your final response.
"""


def slugify(title: str) -> str:
    """Convert a task title to a branch-safe slug."""
    # Strip common prefixes
    title = title.removeprefix("[Feature] ").removeprefix("[feature] ")
    slug = title.lower()
    slug = "".join(c if c.isalnum() or c == "-" else "-" for c in slug)
    slug = "-".join(part for part in slug.split("-") if part)
    return slug[:50]


def main(dry_run: bool = False) -> None:
    log.info("Nightwatch build starting (dry_run=%s)", dry_run)

    # Get feature tasks
    tasks = get_tasks(tags=["nightwatch", "feature"], status="TODO", limit=MAX_PRS)
    if not tasks:
        log.info("No feature tasks to process")
        write_status_file("brain/memory/nightwatch-improve-status.md", (
            f"# Nightwatch Improve Status\n\n"
            f"Last run: {datetime.now().isoformat()}\n"
            f"Mode: build\n"
            f"PRs created: 0\n"
            f"Tasks available: 0\n"
        ))
        return

    log.info("Found %d feature tasks to process", len(tasks))

    if dry_run:
        for t in tasks:
            log.info("  [DRY RUN] Task: %s (priority=%s)", t.get("title"), t.get("priority"))
        return

    # Process each task
    date = today_str()
    prs_created = []
    tasks_skipped = []

    for task in tasks[:MAX_PRS]:
        task_id = task.get("id", "unknown")
        title = task.get("title", "untitled")
        slug = slugify(title)
        branch = f"feature/{date}/{slug}"
        task["_branch"] = branch

        log.info("Processing feature: %s (%s)", title, task_id)

        worktree_path = None
        try:
            worktree_path = create_worktree(branch)

            prompt = build_feature_prompt(task)
            result = invoke_claude_code(
                cwd=worktree_path,
                prompt=prompt,
                system_prompt=BUILD_SYSTEM_PROMPT,
                allowed_tools=BUILD_TOOLS,
                budget=BUILD_BUDGET,
                timeout=900,  # 15 min for features
            )

            pr_url = extract_pr_url(result)
            if pr_url:
                log.info("PR created: %s", pr_url)
                prs_created.append({"task_id": task_id, "title": title, "pr_url": pr_url})
                resolve_nightwatch_task(task_id, f"Draft PR created: {pr_url}")
            else:
                error = result.get("error", "No PR created — likely test/build failure")
                log.warning("No PR for task %s: %s", task_id, error)
                tasks_skipped.append({"task_id": task_id, "title": title, "reason": error})

        except Exception as e:
            log.error("Error processing task %s: %s", task_id, e)
            tasks_skipped.append({"task_id": task_id, "title": title, "reason": str(e)})

        finally:
            if worktree_path:
                cleanup_worktree(worktree_path)

    # Write results
    now = datetime.now().isoformat()

    # Update nightwatch_log
    nightwatch_log = read_memory_block("nightwatch_log")
    log_entry = f"[{date}] build: PRs created: {len(prs_created)}, skipped: {len(tasks_skipped)}"
    if prs_created:
        log_entry += "\n" + "\n".join(
            f"  PR: {pr['pr_url']} ({pr['title']})" for pr in prs_created
        )
    updated_log = nightwatch_log.rstrip() + "\n" + log_entry + "\n"
    lines = updated_log.strip().split("\n")
    if len(lines) > 100:
        lines = lines[-100:]
    write_memory_block("nightwatch_log", "\n".join(lines))

    # Write status
    pr_list = "\n".join(
        f"- [{pr['title']}]({pr['pr_url']})" for pr in prs_created
    ) or "None"
    skipped_list = "\n".join(
        f"- {s['title']}: {s['reason'][:80]}" for s in tasks_skipped
    ) or "None"

    write_status_file("brain/memory/nightwatch-improve-status.md", (
        f"# Nightwatch Improve Status\n\n"
        f"Last run: {now}\n"
        f"Mode: build\n"
        f"PRs created: {len(prs_created)}\n"
        f"Tasks skipped: {len(tasks_skipped)}\n\n"
        f"## PRs Created\n{pr_list}\n\n"
        f"## Skipped\n{skipped_list}\n"
    ))

    # Create review task if PRs were created
    if prs_created:
        pr_summary = "\n".join(
            f"- {pr['title']}: {pr['pr_url']}" for pr in prs_created
        )
        create_nightwatch_task(
            title=f"Review Nightwatch Feature PRs — {date}",
            body=(
                f"{len(prs_created)} feature PR(s) awaiting review:\n\n"
                f"{pr_summary}\n\n"
                f"Generated by Nightwatch Self-Improving"
            ),
            tags=["nightwatch", "feature", "review-needed", "needs-philip"],
            priority="high",
            assigned_to="main",
        )

    log.info(
        "Nightwatch build complete: %d PRs created, %d skipped",
        len(prs_created), len(tasks_skipped),
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Nightwatch Build")
    parser.add_argument("--dry-run", action="store_true", help="Query tasks only, skip Claude Code")
    args = parser.parse_args()
    main(dry_run=args.dry_run)
