name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to trigger the bug.
      placeholder: |
        1. Run `robothor engine start`
        2. Send a message via Telegram
        3. Observe error in logs
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system is affected?
      options:
        - Engine (agent runner)
        - Memory / RAG
        - CRM / Bridge
        - Vision
        - Voice
        - Health (Garmin)
        - Helm (dashboard)
        - CLI
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: "3.12"

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Ubuntu 24.04"

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any error output or stack traces.
      render: shell
