name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve, or what opportunity does it create?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system would this affect?
      options:
        - Engine (agent runner)
        - Memory / RAG
        - CRM / Bridge
        - Vision
        - Voice
        - Health (Garmin)
        - Helm (dashboard)
        - CLI
        - Other
    validations:
      required: true
