"""
Genus OS init — interactive setup wizard.

Guides new users from zero to a working system:
  1. Check prerequisites (Python, psql, Redis, Ollama, Docker)
  2. Prompt for database configuration
  3. Create workspace directories
  4. Run database migrations
  5. Pull required Ollama models
  6. Write .env configuration file
  7. Optionally generate docker-compose.yml and start containers

Usage:
    robothor init              # Interactive setup
    robothor init --yes        # Non-interactive with env defaults
    robothor init --docker     # Use Docker for infrastructure
"""

from __future__ import annotations

import getpass
import json
import os
import platform
import secrets
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

import httpx
import yaml

from robothor.config import DatabaseConfig, OllamaConfig, RedisConfig

# Models required for the RAG pipeline
REQUIRED_MODELS = ["qwen3-embedding:0.6b", "Qwen3-Reranker-0.6B:F16"]

DOCKER_COMPOSE_TEMPLATE = """\
# Generated by: robothor init --docker
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: robothor-postgres
    restart: always
    environment:
      POSTGRES_DB: robothor_memory
      POSTGRES_USER: robothor
      POSTGRES_PASSWORD: "{db_password}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U robothor -d robothor_memory"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: robothor-redis
    restart: always
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: robothor-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      OLLAMA_HOST: "0.0.0.0"

volumes:
  postgres_data:
  redis_data:
  ollama_data:
"""


def _save_init_state(workspace: Path, step: str, status: str) -> None:
    """Write init progress to .robothor/init_state.yaml for resume support."""
    state_dir = workspace / ".robothor"
    state_dir.mkdir(parents=True, exist_ok=True)
    state_path = state_dir / "init_state.yaml"

    state: dict[str, Any] = {}
    if state_path.exists():
        state = yaml.safe_load(state_path.read_text()) or {}
    state[step] = status

    state_path.write_text(yaml.dump(state, default_flow_style=False))


def _load_init_state(workspace: Path) -> dict[str, str]:
    """Load init progress from .robothor/init_state.yaml."""
    state_path = workspace / ".robothor" / "init_state.yaml"
    if not state_path.exists():
        return {}
    return yaml.safe_load(state_path.read_text()) or {}


def run_init(args: Any) -> int:
    """Main orchestrator for the init wizard."""
    print()
    print("  Genus OS Setup")
    print("  " + "=" * 14)
    print()

    # 1. Check prerequisites
    print("  Checking prerequisites...")
    prereqs = check_prerequisites(
        docker_required=getattr(args, "docker", False),
    )
    _print_prerequisites(prereqs)
    print()

    # Bail on missing required prerequisites
    missing_required = [p for p in prereqs if p["required"] and not p["found"]]
    if missing_required:
        print("  Cannot continue — install the required tools above.")
        return 1

    # 2. Identity
    workspace = Path(getattr(args, "workspace", None) or Path.home() / "robothor")
    yes = getattr(args, "yes", False)
    docker = getattr(args, "docker", False)
    skip_models = getattr(args, "skip_models", False)
    skip_db = getattr(args, "skip_db", False)

    # Check for existing installation
    env_exists = (workspace / ".env").exists()
    config_exists = (workspace / ".robothor" / "config.yaml").exists()
    if env_exists or config_exists:
        print("  Existing installation detected.")
        if not yes:
            choice = input("  [U]pgrade existing / [F]resh install / [Q]uit? [U]: ").strip().lower()
            if choice == "q":
                return 0
            if choice == "f":
                pass  # Continue with full setup
            else:
                # Upgrade mode: load init_state and skip completed steps
                pass
        # In --yes mode, default to upgrade behavior

    if yes:
        ai_name = os.environ.get("ROBOTHOR_AI_NAME", "Robothor")
        owner_name = os.environ.get("ROBOTHOR_OWNER_NAME", "")
        owner_email = os.environ.get("ROBOTHOR_OWNER_EMAIL", "")
        ai_email = os.environ.get("ROBOTHOR_AI_EMAIL", "")
        timezone = os.environ.get("ROBOTHOR_TIMEZONE", "America/New_York")
    else:
        print("  Identity:")
        ai_name = input("    What should your AI be called? [Robothor]: ").strip() or "Robothor"
        owner_name = input("    Your name: ").strip()
        owner_email = input("    Your email: ").strip()
        ai_email = input(f"    {ai_name}'s email (leave blank to skip): ").strip()
        timezone = input("    Your timezone [America/New_York]: ").strip() or "America/New_York"
        print()

    # 3. Docker mode: generate compose and start containers
    db_password = ""
    if docker:
        db_password = os.environ.get("ROBOTHOR_DB_PASSWORD", "") or secrets.token_urlsafe(16)
        if not yes:
            pw = getpass.getpass(f"  Docker DB password [{db_password}]: ")
            if pw:
                db_password = pw

    # 4. Prompt for DB config (interactive only, non-Docker)
    if docker:
        db_config = DatabaseConfig(
            host="127.0.0.1",
            port=5432,
            name="robothor_memory",
            user="robothor",
            password=db_password,
        )
    elif yes:
        db_config = _db_config_from_env()
    else:
        db_config = prompt_db_config()

    redis_config = _redis_config_from_env()
    ollama_config = _ollama_config_from_env()

    # Load init state for resume support
    init_state = _load_init_state(workspace)

    # 5. Create workspace (skip if completed)
    if init_state.get("workspace") != "completed":
        print(f"  Creating workspace {workspace} ...", end=" ", flush=True)
        create_workspace(workspace)
        print("done")
        _save_init_state(workspace, "workspace", "completed")
    else:
        print(f"  Creating workspace {workspace} ... skipped (exists)")

    # 6. Docker mode: generate compose, start, wait
    if docker:
        if init_state.get("docker") != "completed":
            compose_path = generate_docker_compose(workspace, db_password)
            print(f"  Generated {compose_path}")
            print("  Starting Docker containers ...", end=" ", flush=True)
            if wait_for_services(workspace, timeout=90):
                print("done")
            else:
                print("timed out (containers may still be starting)")
            _save_init_state(workspace, "docker", "completed")
        else:
            print("  Docker containers ... skipped (exists)")

    # 7. Run migration
    if not skip_db:
        if init_state.get("migration") != "completed":
            print("  Running migration ...", end=" ", flush=True)
            table_count = run_migration(db_config)
            if table_count >= 0:
                print(f"{table_count} tables created")
                _save_init_state(workspace, "migration", "completed")
            else:
                print("FAILED")
                print("  Error: Database migration failed. Check connection settings:")
                print(f"    Host: {db_config.host}:{db_config.port}")
                print(f"    Database: {db_config.name}")
                print(f"    User: {db_config.user}")
                return 1
        else:
            print("  Running migration ... skipped (completed)")

        # Validate database connection
        if init_state.get("db_validate") != "completed":
            print("  Validating database ...", end=" ", flush=True)
            try:
                import psycopg2

                conn = psycopg2.connect(**db_config.dict, connect_timeout=5)
                with conn.cursor() as cur:
                    cur.execute("SELECT 1")
                conn.close()
                print("connected")
                _save_init_state(workspace, "db_validate", "completed")
            except Exception as e:
                print(f"FAILED ({e})")
                return 1
        else:
            print("  Validating database ... skipped (verified)")

    # 8. Pull Ollama models
    if not skip_models:
        if init_state.get("models") != "completed":
            pull_ollama_models(ollama_config.base_url, REQUIRED_MODELS)
            _save_init_state(workspace, "models", "completed")
        else:
            print("  Pulling models ... skipped (completed)")

    # 9. Subsystem selection
    profiles: list[str] = []
    if not yes:
        profiles = prompt_subsystems()
    print()

    # 10. Generate vault master key
    if init_state.get("vault") != "completed":
        print("  Generating vault master key ...", end=" ", flush=True)
        setup_vault_key(workspace)
        print("done")
        _save_init_state(workspace, "vault", "completed")
    else:
        print("  Generating vault master key ... skipped (exists)")

    # 11. Write env file
    if init_state.get("env_file") != "completed":
        env_path = workspace / ".env"
        wrote = write_env_file(
            env_path,
            db_config,
            redis_config,
            ollama_config,
            owner_name=owner_name,
            ai_name=ai_name,
            owner_email=owner_email,
            ai_email=ai_email,
            timezone=timezone,
            profiles=profiles,
            yes=yes,
        )
        if wrote:
            print(f"  Saving config to {env_path} ... done")
            _save_init_state(workspace, "env_file", "completed")
    else:
        env_path = workspace / ".env"
        print(f"  Saving config to {env_path} ... skipped (exists)")

    # 12. Resolve template variables in CLAUDE.md files
    for fname in ("CLAUDE.md", "AGENT_BUILDER.md"):
        md_path = workspace / fname
        if md_path.exists():
            content = md_path.read_text()
            content = content.replace("{{ai_name}}", ai_name)
            content = content.replace("{{owner_name}}", owner_name)
            md_path.write_text(content)

    # 13. Agent template setup (if templates exist)
    if not yes:
        _offer_agent_setup(workspace)

    # Summary
    print()
    print("  \u2713 Genus OS initialized")
    print(f"    AI Name:     {ai_name}")
    print(f"    Workspace:   {workspace}")
    print(f"    Database:    postgresql://{db_config.host}:{db_config.port}/{db_config.name}")

    # Show installed models
    model_names = ", ".join(REQUIRED_MODELS) if not skip_models else "skipped"
    print(f"    Models:      {model_names}")

    # Count installed agents
    agent_dir = workspace / "docs" / "agents"
    agent_count = len(list(agent_dir.glob("*.yaml"))) if agent_dir.exists() else 0
    print(f"    Agents:      {agent_count} installed", end="")
    if agent_count == 0:
        print(" (run: robothor agent install --preset standard)", end="")
    print()

    # Engine status
    print("    Engine:      not running (run: sudo systemctl start robothor-engine)")

    print()
    print("  Next steps:")
    print("    1. robothor agent install --preset standard")
    print("    2. sudo systemctl start robothor-engine")
    print("    3. Open Claude Code for identity setup")
    print()
    return 0


def check_prerequisites(*, docker_required: bool = False) -> list[dict[str, Any]]:
    """Check for required and optional tools.

    Returns a list of dicts: {name, found, detail, required, hint}.
    """
    results = []

    # Python (always present)
    results.append(
        {
            "name": "Python",
            "found": True,
            "detail": f"{sys.version.split()[0]}",
            "required": True,
            "hint": "",
        }
    )

    # psql
    psql = shutil.which("psql")
    results.append(
        {
            "name": "PostgreSQL (psql)",
            "found": psql is not None,
            "detail": "found" if psql else "not found",
            "required": False,
            "hint": _install_hint("postgresql-client", "postgresql"),
        }
    )

    # redis-cli
    redis_cli = shutil.which("redis-cli")
    results.append(
        {
            "name": "Redis (redis-cli)",
            "found": redis_cli is not None,
            "detail": "found" if redis_cli else "not found",
            "required": False,
            "hint": _install_hint("redis-server", "redis"),
        }
    )

    # Ollama
    ollama_found = False
    ollama_detail = "not reachable"
    try:
        base_url = os.environ.get("ROBOTHOR_OLLAMA_HOST", "127.0.0.1")
        port = os.environ.get("ROBOTHOR_OLLAMA_PORT", "11434")
        resp = httpx.get(f"http://{base_url}:{port}/api/tags", timeout=3)
        resp.raise_for_status()
        models = resp.json().get("models", [])
        ollama_found = True
        ollama_detail = f"{len(models)} model(s) loaded"
    except Exception:
        ollama_detail = "not reachable"
    results.append(
        {
            "name": "Ollama",
            "found": ollama_found,
            "detail": ollama_detail,
            "required": False,
            "hint": "curl -fsSL https://ollama.com/install.sh | sh",
        }
    )

    # Docker (required only with --docker)
    docker_bin = shutil.which("docker")
    results.append(
        {
            "name": "Docker",
            "found": docker_bin is not None,
            "detail": "found" if docker_bin else "not found",
            "required": docker_required,
            "hint": "https://docs.docker.com/engine/install/",
        }
    )

    return results


def prompt_db_config() -> DatabaseConfig:
    """Interactive prompts for database configuration."""
    defaults = _db_config_from_env()
    print("  Database configuration:")

    host = input(f"    Host [{defaults.host}]: ").strip() or defaults.host
    port_str = input(f"    Port [{defaults.port}]: ").strip()
    port = int(port_str) if port_str else defaults.port
    name = input(f"    Database [{defaults.name}]: ").strip() or defaults.name
    user = input(f"    User [{defaults.user}]: ").strip() or defaults.user
    password = getpass.getpass("    Password: ") if not defaults.password else defaults.password

    print()
    return DatabaseConfig(host=host, port=port, name=name, user=user, password=password)


def prompt_subsystems() -> list[str]:
    """Interactive multi-select for optional Docker Compose profiles."""
    options = [
        ("monitoring", "Monitoring (Uptime Kuma)", "web dashboard for service health"),
        ("tts", "Voice synthesis (Kokoro TTS)", "local text-to-speech"),
        ("media", "Webcam/vision (MediaMTX)", "RTSP/HLS camera streaming"),
        ("tunnel", "Reverse proxy (Cloudflare tunnel)", "secure external access"),
    ]
    print("  Subsystems (optional Docker services):")
    for i, (_, label, desc) in enumerate(options, 1):
        print(f"    {i}. {label} — {desc}")
    selection = input("  Enable (comma-separated numbers, or Enter to skip): ").strip()
    if not selection:
        return []
    profiles = []
    for part in selection.split(","):
        part = part.strip()
        if part.isdigit():
            idx = int(part) - 1
            if 0 <= idx < len(options):
                profiles.append(options[idx][0])
    if profiles:
        print(f"  Enabled: {', '.join(profiles)}")
    return profiles


def setup_vault_key(workspace: Path) -> Path:
    """Generate vault master key if it doesn't exist."""
    from robothor.vault.crypto import init_master_key

    return init_master_key(workspace)


def create_workspace(path: Path) -> None:
    """Create workspace directory structure with brain/ scaffold from templates."""
    path.mkdir(parents=True, exist_ok=True)
    (path / "memory").mkdir(exist_ok=True)
    (path / "faces").mkdir(exist_ok=True)

    # Brain directory — identity, runtime state, agent instructions
    brain = path / "brain"
    brain.mkdir(exist_ok=True)
    (brain / "memory").mkdir(exist_ok=True)

    # Docs directories — agent manifests and workflows
    docs = path / "docs"
    (docs / "agents").mkdir(parents=True, exist_ok=True)
    (docs / "workflows").mkdir(parents=True, exist_ok=True)

    # Copy template files into brain/ (never overwrite existing)
    template_dir = _find_template_dir()
    if template_dir:
        brain_templates = [
            "SOUL.md",
            "IDENTITY.md",
            "AGENTS.md",
            "TOOLS.md",
            "HEARTBEAT.md",
            "USER.md",
            "BOOTSTRAP.md",
        ]
        for filename in brain_templates:
            src = template_dir / filename
            dst = brain / filename
            if src.exists() and not dst.exists():
                dst.write_text(src.read_text())

        # Copy agent manifest template to docs/agents/
        for name in ("agent-manifest.yaml", "agent-instructions.md"):
            src = template_dir / name
            dst = docs / "agents" / name
            if src.exists() and not dst.exists():
                dst.write_text(src.read_text())

        # Copy CLAUDE.md files to workspace root
        for fname in ("CLAUDE.md", "AGENT_BUILDER.md", "ONBOARDING.md"):
            src = template_dir / fname
            dst = path / fname
            if src.exists() and not dst.exists():
                dst.write_text(src.read_text())


def _find_template_dir() -> Path | None:
    """Locate the templates/ directory (bundled or in-repo)."""
    # Bundled in wheel
    bundled = Path(__file__).parent / "templates"
    if bundled.is_dir():
        return bundled
    # Development: repo root
    repo_root = Path(__file__).parent.parent
    dev_path = repo_root / "templates"
    if dev_path.is_dir():
        return dev_path
    return None


def run_migration(db_config: DatabaseConfig) -> int:
    """Run database migration. Returns table count on success, -1 on failure."""
    from robothor.cli import _find_migration_sql

    sql = _find_migration_sql()
    if sql is None:
        return -1

    try:
        import psycopg2

        conn = psycopg2.connect(**db_config.dict, connect_timeout=5)
        conn.autocommit = True
        with conn.cursor() as cur:
            cur.execute(sql)
            # Count tables
            cur.execute(
                "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public'"
            )
            row = cur.fetchone()
            count: int = row[0] if row else 0
        conn.close()
        return count
    except Exception:
        return -1


def pull_ollama_models(base_url: str, models: list[str]) -> None:
    """Pull required Ollama models with progress output."""
    for model in models:
        print(f"  Pulling {model} ...", end=" ", flush=True)
        try:
            with httpx.stream(
                "POST",
                f"{base_url}/api/pull",
                json={"name": model},
                timeout=httpx.Timeout(5.0, read=600.0),
            ) as resp:
                resp.raise_for_status()
                last_status = ""
                for line in resp.iter_lines():
                    if not line:
                        continue
                    try:
                        data = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    status = data.get("status", "")
                    if status != last_status:
                        last_status = status
                print("done")
        except Exception as e:
            print(f"failed ({e})")


def write_env_file(
    path: Path,
    db: DatabaseConfig,
    redis: RedisConfig,
    ollama: OllamaConfig,
    *,
    owner_name: str = "",
    ai_name: str = "Robothor",
    owner_email: str = "",
    ai_email: str = "",
    timezone: str = "America/New_York",
    profiles: list[str] | None = None,
    yes: bool = False,
) -> bool:
    """Write .env file with configuration. Returns True if written."""
    if path.exists() and not yes:
        overwrite = input(f"  {path} exists. Overwrite? [y/N]: ").strip().lower()
        if overwrite != "y":
            print(f"  Keeping existing {path}")
            return False

    # Secrets are NEVER written to .env — use SOPS or environment variables
    lines = [
        f"ROBOTHOR_OWNER_NAME={owner_name}",
        f"ROBOTHOR_AI_NAME={ai_name}",
        f"ROBOTHOR_OWNER_EMAIL={owner_email}",
        f"ROBOTHOR_AI_EMAIL={ai_email}",
        f"ROBOTHOR_TIMEZONE={timezone}",
        f"ROBOTHOR_DB_HOST={db.host}",
        f"ROBOTHOR_DB_PORT={db.port}",
        f"ROBOTHOR_DB_NAME={db.name}",
        f"ROBOTHOR_DB_USER={db.user}",
        "# ROBOTHOR_DB_PASSWORD — set via SOPS secrets or env, not stored here",
        "ROBOTHOR_DB_PASSWORD=",
        f"ROBOTHOR_REDIS_HOST={redis.host}",
        f"ROBOTHOR_REDIS_PORT={redis.port}",
        f"ROBOTHOR_OLLAMA_HOST={ollama.host}",
        f"ROBOTHOR_OLLAMA_PORT={ollama.port}",
        f"ROBOTHOR_WORKSPACE={path.parent}",
    ]
    if profiles:
        lines.append(f"COMPOSE_PROFILES={','.join(profiles)}")
    path.write_text("\n".join(lines) + "\n")
    return True


def generate_docker_compose(workspace: Path, db_password: str) -> Path:
    """Generate a docker-compose.yml in the workspace directory."""
    compose_path = workspace / "docker-compose.yml"
    content = DOCKER_COMPOSE_TEMPLATE.format(db_password=db_password)
    compose_path.write_text(content)
    return compose_path


def wait_for_services(workspace: Path, timeout: int = 60) -> bool:
    """Start Docker containers and wait for health checks."""
    compose_file = workspace / "docker-compose.yml"
    if not compose_file.exists():
        return False

    result = subprocess.run(
        ["docker", "compose", "-f", str(compose_file), "up", "-d"],
        capture_output=True,
        text=True,
        cwd=str(workspace),
    )
    if result.returncode != 0:
        print(f"\n  Docker error: {result.stderr.strip()}")
        return False

    # Poll for PG readiness
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            import psycopg2

            conn = psycopg2.connect(
                host="127.0.0.1",
                port=5432,
                dbname="robothor_memory",
                user="robothor",
                password="robothor",
                connect_timeout=2,
            )
            conn.close()
            return True
        except Exception:
            time.sleep(2)

    return False


# --- Private helpers ---


def _db_config_from_env() -> DatabaseConfig:
    """Build DatabaseConfig from environment variables."""
    return DatabaseConfig(
        host=os.environ.get("ROBOTHOR_DB_HOST", "127.0.0.1"),
        port=int(os.environ.get("ROBOTHOR_DB_PORT", "5432")),
        name=os.environ.get("ROBOTHOR_DB_NAME", "robothor_memory"),
        user=os.environ.get("ROBOTHOR_DB_USER", os.environ.get("USER", "robothor")),
        password=os.environ.get("ROBOTHOR_DB_PASSWORD", ""),
    )


def _redis_config_from_env() -> RedisConfig:
    """Build RedisConfig from environment variables."""
    return RedisConfig(
        host=os.environ.get("ROBOTHOR_REDIS_HOST", "127.0.0.1"),
        port=int(os.environ.get("ROBOTHOR_REDIS_PORT", "6379")),
        db=int(os.environ.get("ROBOTHOR_REDIS_DB", "0")),
        password=os.environ.get("ROBOTHOR_REDIS_PASSWORD", ""),
    )


def _ollama_config_from_env() -> OllamaConfig:
    """Build OllamaConfig from environment variables."""
    return OllamaConfig(
        host=os.environ.get("ROBOTHOR_OLLAMA_HOST", "127.0.0.1"),
        port=int(os.environ.get("ROBOTHOR_OLLAMA_PORT", "11434")),
    )


def _offer_agent_setup(workspace: Path) -> None:
    """Offer agent preset installation if templates are available."""
    try:
        from robothor.templates.catalog import Catalog

        catalog = Catalog()
        templates = catalog.list_available_templates()
        if not templates:
            return

        print()
        answer = input("  Set up agent templates? [y/N]: ").strip().lower()
        if answer != "y":
            return

        # Delegate to the agent setup wizard
        from robothor.cli import _cmd_agent_setup

        _cmd_agent_setup()
    except Exception:
        # Template system is optional — don't fail init if it's broken
        pass


def _install_hint(apt_pkg: str, brew_pkg: str) -> str:
    """Return platform-appropriate install hint."""
    if platform.system() == "Darwin":
        return f"brew install {brew_pkg}"
    return f"apt install {apt_pkg}  OR  brew install {brew_pkg}"


def _print_prerequisites(prereqs: list[dict[str, Any]]) -> None:
    """Print formatted prerequisite check results."""
    for p in prereqs:
        mark = "+" if p["found"] else "x"
        line = f"    {mark} {p['name']}"
        if p["found"]:
            line += f" ({p['detail']})"
        print(line)
        if not p["found"] and p["hint"]:
            print(f"      -> {p['hint']}")
