"""Tool handler modules — each exposes a HANDLERS dict mapping tool name → async handler."""

from __future__ import annotations

from robothor.engine.tools.handlers import (  # noqa: F401
    apollo,
    benchmark,
    browser,
    crm,
    desktop,
    devops_metrics,
    experiment,
    federation,
    filesystem,
    git,
    github_api,
    gws,
    identity,
    jira,
    mcp_client,
    memory,
    messaging,
    observability,
    pdf,
    pf,
    reasoning,
    reports,
    skills,
    spawn,
    timing,
    todolist,
    vault,
    vision,
    voice,
    web,
)
